classDiagram
  Ambriel

  Arissa

  Auri --> Faendal
  Auri --> Inigo
  Auri --> Kaidan
  Auri --> Lucien
  Auri --> Serana

  Aurlyn_Dawnstone
  Hoth

  Inigo --> Auri
  Inigo --> Lucien
  Inigo --> Serana
  Inigo --> Vilja

  Kaidan

  Lucien --> AnnaNPCs_Anduniel
  Lucien --> AnnaNPCs_Elyndra
  Lucien --> AnnaNPCs_Lyra
  Lucien --> AnnaNPCs_Mareen
  Lucien --> AnnaNPCs_Nadina
  Lucien --> AnnaNPCs_Valyen
  Lucien --> CreationClub_Bone_Wolf
  Lucien --> CreationClub_Dwarven_Armored_Mudcrab
  Lucien --> CreationClub_Gogh
  Lucien --> Auri
  Lucien --> Celia_the_Kettle_Maiden
  Lucien --> Delphine
  Lucien --> Esbern
  Lucien --> Hoth
  Lucien --> Inigo
  Lucien --> J_zargo
  Lucien --> Kaidan
  Lucien --> Lydia
  Lucien --> Meeko
  Lucien --> Recorder
  Lucien --> Sofia
  Lucien --> Vigilance
  Lucien --> Vilja

  Mirai --> Recorder
  Mirai --> Sofia

  Nebarra --> Inigo
  Nebarra --> Lucifer
  Nebarra --> Skeever

  Shirley

  Sofia

  Vilja --> Aela
  Vilja --> Argis
  Vilja --> Brelyna
  Vilja --> Erik
  Vilja --> Farkas
  Vilja --> Inigo
  Vilja --> J_zargo
  Vilja --> Jenassa
  Vilja --> Jordis
  Vilja --> Lydia
  Vilja --> Marcurio
  Vilja --> Onmund
  Vilja --> Sven
